### ISSUE TITLE
"ImportError No module named pathlib" on startup

### ISSUE THREAD

**Issue by still-dreaming-1** [Kuniwak/vint#287]
I just did a fresh install of vint via `pip install vim-vint`. Then when I run `vint`:

> Traceback (most recent call last):
>   File "/home/jesse/.local/bin/vint", line 7, in <module>
>     from vint import main
>   File "/home/jesse/.local/lib/python2.7/site-packages/vint/__init__.py", line 1, in <module>
>     from vint.bootstrap import (
>   File "/home/jesse/.local/lib/python2.7/site-packages/vint/bootstrap.py", line 3, in <module>
>     from pathlib import Path
> ImportError: No module named pathlib

Here is my .vintrc.yaml:

```
cmdargs:
    env:
        neovim: true
policies:
    # Disable a violation
    ProhibitImplicitScopeVariable:
        enabled: false
```

I also tried it with only the neovim:true setting, with a blank settings file, and I even tried deleting the settings file, but I get the same output on running vint.

I'm on Ubuntu 16.04 LTS. Additional system info:

> ▷ which python
> /usr/bin/python
> ▷ python --version
> Python 2.7.12
> ▷ which pip
> /usr/bin/pip
> ▷ pip --version
> pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
